### ISSUE TITLE
Localization string in onboarding not replaced

### ISSUE THREAD

**Issue by timschoch** [nico-martin/refugee-camp-frontend#19]
The localization string isn't replaced here:
https://github.com/nico-martin/refugee-camp-frontend/blob/bb10809bf15d8d3c712b94a85d01f225ee87d0fc/src/app/components/Onboarding/RegistrationNumber.tsx#L33

![grafik](https://user-images.githubusercontent.com/10527318/92279685-2186bd80-eef8-11ea-8c97-d82940f81cb9.png)

**Comment by nico-martin** [comment]
@simonmesserli, is there a reason for this commit?
https://github.com/simonmesserli/refugee-camp-frontend/commit/9eced5200bd0c3b4c6efe581df4c55714e7e43aa

**Comment by simonmesserli** [comment]
I first thought that this is the source of the error. but it was in the external spreadsheet, so i reverted the change :) 
commit message: revert change, because mistake is in external trans docs
